import Image from "next/image"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import type { PageContent, Section } from "@/lib/types"
import { cn } from "@/lib/utils"

function Hero({ s }: { s: Section }) {
  return (
    <section className="relative overflow-hidden bg-gradient-to-br from-emerald-50 to-white border-b">
      <div className="mx-auto max-w-5xl px-6 py-12 md:py-16 grid md:grid-cols-2 gap-8 items-center">
        <div>
          <h1 className="text-3xl md:text-5xl font-bold tracking-tight">{s.title || "Welcome"}</h1>
          <p className="mt-3 text-muted-foreground">
            {s.body || "Describe your offering in a concise, compelling way."}
          </p>
          <div className="mt-6 flex gap-3">
            <Button>Get Started</Button>
            <Button variant="outline">Learn More</Button>
          </div>
        </div>
        <div className="relative aspect-[4/3] rounded-lg overflow-hidden ring-1 ring-black/5">
          <Image
            src={s.image || "/placeholder.svg?height=600&width=800&query=hero%20illustration%20for%20website"}
            alt={s.title || "Hero"}
            width={800}
            height={600}
            className="object-cover w-full h-full"
            priority
          />
        </div>
      </div>
    </section>
  )
}

function About({ s }: { s: Section }) {
  return (
    <section className="mx-auto max-w-5xl px-6 py-10">
      <div className="grid md:grid-cols-3 gap-6 items-start">
        <div className="md:col-span-1">
          <h2 className="text-2xl font-semibold">{s.title || "About Us"}</h2>
        </div>
        <div className="md:col-span-2 text-muted-foreground">
          {s.body || "Share your story, mission, and what makes you different."}
        </div>
      </div>
    </section>
  )
}

function Contact({ s }: { s: Section }) {
  return (
    <section className="mx-auto max-w-5xl px-6 pb-12">
      <Card>
        <CardContent className="p-6">
          <h3 className="text-xl font-semibold">{s.title || "Contact"}</h3>
          <p className="mt-2 text-muted-foreground">
            {s.body || "Reach out for quotes, collaborations, or questions."}
          </p>
          <div className="mt-4 text-sm">
            <div>Email: hello@example.com</div>
            <div>Phone: (555) 123-4567</div>
          </div>
        </CardContent>
      </Card>
    </section>
  )
}

function Generic({ s }: { s: Section }) {
  return (
    <section className="mx-auto max-w-5xl px-6 py-8">
      <h3 className="text-xl font-semibold">{s.title || s.type || "Section"}</h3>
      {s.body && <p className="mt-2 text-muted-foreground">{s.body}</p>}
    </section>
  )
}

export default function PreviewPage({ page, dense = true }: { page: PageContent; dense?: boolean }) {
  const sections = page.sections ?? []

  return (
    <div className={cn(dense ? "" : "pt-6")}>
      {sections.map((s, idx) => {
        const t = (s.type || "").toLowerCase()
        if (t === "hero") return <Hero s={s} key={idx} />
        if (t === "about") return <About s={s} key={idx} />
        if (t === "contact") return <Contact s={s} key={idx} />
        return <Generic s={s} key={idx} />
      })}
      {sections.length === 0 && (
        <section className="p-6">
          <div className="text-center text-muted-foreground">No sections available yet.</div>
        </section>
      )}
      <footer className="border-t py-6 text-center text-xs text-muted-foreground">Generated by PromptSite</footer>
    </div>
  )
}
